### ISSUE TITLE
please provide examples for create button and detect button press (Featherwing 3.5")

### ISSUE THREAD

**Issue by dsyleixa** [adafruit/Adafruit_HX8357_Library#12]
please provide examples for button press 
(Featherwing 3.5", Feather Huzzah, <Adafruit_STMPE610.h> , <Adafruit_HX8357.h>),
a) landscape
b) portrait

**Comment by dsyleixa** [comment]
PS,
as I just noticed the PR about a menu system:
The basic example I actually mean is just about:

init to landscape or portrait format (arbitrarily)
create 2 different buttons
detect touch position if touched anywhere
show touch (x,y) position on the screen
change the specific button colors if a button was hit once or perhaps by double-click (e.g., inverse) 
write a notification on the screen if a botton was released (i.e., in a proprietary program used to trigger an arbitrary  function by button press)
make it possible to undo an button hit if that might have happened just incidentally.

**Comment by ladyada** [comment]
if you can write a documented and clearly written example, we'd love to have it as a PR :)

**Comment by dsyleixa** [comment]
Your reply is a little weird, probably you are missing my point:
if I could write touch screen button examples I hadn't written this request for multiple touch screen buttons examples, finally nothing exists at all!
So please provide several basic examples for touch screen button usage!

**Comment by ladyada** [comment]
ok we'll leave this issue open, no guarantee on when we'll get to writing the exact example you like - we've got many many libraries to manage :)

**Comment by dsyleixa** [comment]
thank you!
After all, as already stated, it actually might be more a general GFX Lib issue, because buttons are supposed to be processed there, and so these button press examples will be a huge benefit for all your GFX lib users, not just for the 3.5" Featherwing TFT.
So I would appreciate very much if you could  assign a higher priority to  an issue fix.

**Comment by dsyleixa** [comment]
Now will there soon be some basic code examples for programming buttons?

**Comment by ladyada** [comment]
no ETA on this, we have plenty of bugs to fix in our libraries so this is not a high priority! please don't bump - it won't get it done any faster :) if you want to hire someone to help with custom code needs, check out our jobs board! https://jobs.adafruit.com/

**Comment by makermelissa** [comment]
A button example was merged in today.
