### ISSUE TITLE
Flipping the 3.5 FeatherWing Enable Switch off and on causes reversing

### ISSUE THREAD

**Issue by makermelissa** [adafruit/Adafruit_HX8357_Library#17]
I'm not exactly sure why this is happening, but with the 3.5" TFT FeatherWing and (I'm not sure it makes a difference) a Feather Huzzah, flipping the enable switch off and on causes colors to be drawn in BGR mode rather than RGB mode. Flipping it subsequent times has no effect and it is still drawn as BGR. Resetting on either the feather or wing causes it to go back to RGB. I noticed in the bitmapdraw_featherwing example, the touch on the longer axis is mirrored as well.

**Comment by makermelissa** [comment]
I noticed this happens with both the ImageReader example and the graphicstest.

**Comment by ladyada** [comment]
could be it doenst re-init or half-inits. maybe add a delay at start, to stabilize the display before you start configuring it

**Comment by makermelissa** [comment]
Ok, I’ll try that.

**Comment by makermelissa** [comment]
Changing the first delay in the init sequence from 10 to 100 seems to have solved the issue.
