### ISSUE TITLE
Graphics test fails on Feather M4 when SD card inserted

### ISSUE THREAD

**Issue by makermelissa** [adafruit/Adafruit_HX8357_Library#18]
To reproduce, load the graphicstest_featherwing on a Feather M4 and run. It consistently fails on the testRoundRects() function. Tried using 2 feathers with the same result. This worked fine on a Feather Huzzah.

**Comment by ladyada** [comment]
mysterious - can you dig into why?

**Comment by makermelissa** [comment]
Yep. I was just digging out some more boards to test on.

**Comment by makermelissa** [comment]
This failed on a Feather M0 in the same spot as well.

**Comment by makermelissa** [comment]
Oops, looks like I was wrong about which test. It's the testFilledTriangles() that it fails on. Huzzah32 however failed on testRoundRects().

**Comment by makermelissa** [comment]
Also, I should note that this is failing on the 1.1.1 version of the driver as well as the sendCommand updates I made. It might be a timing issue.

**Comment by makermelissa** [comment]
If it is a timing issue, it may be related to #17 which seemed a little random in its behavior.

**Comment by makermelissa** [comment]
Ok, the plot thickens. The issue only occurs when I have an SD card in the TFT FeatherWing.

**Comment by siddacious** [comment]
🤔

**Comment by makermelissa** [comment]
I’m going to try different SD cards next to see if that makes a difference.

**Comment by makermelissa** [comment]
This seems to only happen with a very specific SD card that I happen to have a bunch of. Since it works with the more popular brands and it's not even necessary for this test, I don't think this is worth trying to fix.
