### ISSUE TITLE
Rebuild after Travis issue fixed

### ISSUE THREAD

**Issue by makermelissa** [adafruit/Adafruit_HX8357_Library#20]
It seems there is an issue with Travis and from what I can narrow it down to has to do with DNS Multicasts causing a Java Error on M4 builds (all examples). However, it builds and runs just fine on the Arduino IDE. I noticed Travis was updated to use Arduino 1.8.9 instead of 1.8.7, but there could have been other updates as well. This issue is more of a reminder to rebuild once that issue is fixed. Alternatively, we could add a test skip for the M4 until then.

**Comment by ladyada** [comment]
m4 revision broke command line arudino will be updated soon

**Comment by makermelissa** [comment]
Rebuilding with new release.
