### ISSUE TITLE
error in drawPixel

### ISSUE THREAD

**Issue by gale3313** [adafruit/Adafruit_HX8357_Library#3]
I believe drawPixel should be revised. 

This line:
  setAddrWindow(x,y,x+1,y+1);

should be:
  setAddrWindow(x,y,x,y);

Otherwise, it seems to be impossible to draw pixels (or lines) on row or column 319 or 479.

For more information, see [https://forums.adafruit.com/viewtopic.php?f=22&t=92900](url)

**Comment by ladyada** [comment]
you're right! i've fixed and also added SPI xactions which will make it more cross-platform. thank you :) :) :)
