### ISSUE TITLE
TFT_CS for NRF52832_FEATHER is incorrect in some samples 

### ISSUE THREAD

**Issue by PhilManning** [adafruit/Adafruit_HX8357_Library#33]
- Arduino board:  Adafruit Feather nRF52 Bluefruit LE - nRF52832

- Arduino IDE version: 1.8.10

The samples gfxbuttontest_feather.ino, graphicstest_featherwing.ino, and touchpaint_featherwing.ino incorrectly have TFT_CS defined to 13.  It should be 31.

bitmapdraw_featherwing has it correctly defined as 31.

**Comment by ladyada** [comment]
woops could you submit a PR? we'd appreciate it :)

**Comment by ladyada** [comment]
closing, this was fixed
