### ISSUE TITLE
library modified for ESP8266

### ISSUE THREAD

**Issue by galed3e3** [adafruit/Adafruit_HX8357_Library#5]
I modified the Adafruit HX8357 library (for the 3.5" TFT) to work with the ESP8266. The modified library files and example graphics sketch can be found at https://forums.adafruit.com/viewtopic.php?f=31&t=103191&p=519156#p519156

**Comment by rikkkurd** [comment]
This does not work for me yet. Please update the default library to work with the ESP8266

**Comment by ladyada** [comment]
fixzed!
