### ISSUE TITLE
Bug in hardware SPI mode writecommand, writedata.

### ISSUE THREAD

**Issue by XekriRedmane** [adafruit/Adafruit_HX8357_Library#6]
- Arduino board:  Teensy 3.2
- Arduino IDE version (found in Arduino -> About Arduino menu):  1.6.11
- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): 
  Run graphicstest in hardware SPI mode. It will just display a white screen. Running in software mode (bitbanging mode) works fine.

The cause is a bug in lines 80 and 96. You are still bit-banging the clock even in hardware SPI mode, which effectively tries to write to address 0 (since clkport in hardware mode is 0). This is no fun for anyone, let alone the processor.

To fix, gate those lines with if (!hwSPI) { ... }. For example:

  if (!hwSPI) {
      *clkport &= ~clkpinmask;
  }

I have done this, and the Teensy is so much happier. The display also now works in hardware SPI mode, which is a good thing I suppose.

**Comment by ladyada** [comment]
fixzed!
